### ISSUE TITLE
Arquivos .wav não estão versionados

### ISSUE THREAD

**Issue by olegon** [gpdmartins/games#1]
Oi, José Guilherme! Tudo bem?

Curti a tua versão do **Scape Invaders**, mas eu não consegui rodar com áudio porque os arquivos *.wav* não estão versionados.

Mas parabéns! Bons estudos!

**Comment by gpdmartins** [comment]
Oi Leadro, tudo certo?

Obrigado, eu havia esqucido de adicionar os .wav!

Valeu!
